package suratmasuk;

import java.io.File;
import java.nio.file.Files;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author WIN 10
 */
public class masuk_share extends javax.swing.JFrame {

    /**
     * Creates new form masuk_share
     */
    public masuk_share() {
        initComponents();
        //setDirektori();
        txtdirektori.setEditable(false);
        populatePaletteList();
    }

    void setDirektori(String direktoriSurat) {
        //String direktorisurat = null;
        txtdirektori.setText(direktoriSurat);
    }

    private void populatePaletteList() {
        DefaultListModel<String> model = new DefaultListModel<>();
        try {
            java.util.List<String> admins = koneksi.conek.getAdmins();
            for (String admin : admins) {
                model.addElement(admin);
            }
        } catch (Exception ex) {
            // Handle error
            ex.printStackTrace();
        }
        Lnomor.setModel(model);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lnomor = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtpesan = new javax.swing.JTextArea();
        txtdirektori = new javax.swing.JFormattedTextField();
        btnsend = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtsubjek = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Pilih Alamat Email Tujuan yang Dibutuhkan !");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jScrollPane1.setViewportView(Lnomor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 307, 74));

        jLabel2.setText("Subject");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        txtpesan.setColumns(20);
        txtpesan.setRows(5);
        jScrollPane2.setViewportView(txtpesan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 229, -1));
        getContentPane().add(txtdirektori, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 307, -1));

        btnsend.setText("Send");
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });
        getContentPane().add(btnsend, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        jLabel3.setText("Body Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        txtsubjek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubjekActionPerformed(evt);
            }
        });
        getContentPane().add(txtsubjek, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 230, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
    String emailpengirim = "raatyms0810@gmail.com";
    String sandiaplikasi = "yrnc yrio vwnm kunj";
    
    // Deklarasikan variabel emailpenerima di luar blok try-catch
    String emailpenerima = null; // Atau beri nilai default jika diperlukan

    try {
        // Ambil data dari List yang dipilih (format: NAMA | EMAIL)
        String selectedValue = Lnomor.getSelectedValue();
        // Pisahkan nama dan email
        String[] parts = selectedValue.split("\\|");
        // Ambil email saja
        emailpenerima = parts[1].trim();
        
        // Membaca file dari direktori yang ditentukan
        String direktori = txtdirektori.getText();
        File attachmentFile = new File(direktori);
        byte[] attachmentBytes = Files.readAllBytes(attachmentFile.toPath());
     
        String subject = txtsubjek.getText();
        String bodyEmail = txtpesan.getText();
        
        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");

        Session session = Session.getInstance(props, new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(emailpengirim, sandiaplikasi);
            }
        });

        Message mess = new MimeMessage(session);
        mess.setFrom(new InternetAddress(emailpengirim));
        mess.setRecipients(Message.RecipientType.TO, InternetAddress.parse(emailpenerima));
        mess.setSubject(subject);
        mess.setText(bodyEmail);
        
        // Membuat bagian lampiran
        MimeBodyPart attachmentPart = new MimeBodyPart();
        attachmentPart.setFileName(attachmentFile.getName());
        attachmentPart.setContent(attachmentBytes, "application/octet-stream");

        // Membuat konten email
        Multipart multipart = new MimeMultipart();
        multipart.addBodyPart(attachmentPart);

        // Membuat bagian teks email
        MimeBodyPart textPart = new MimeBodyPart();
        textPart.setText(bodyEmail);
        multipart.addBodyPart(textPart);

        // Set konten email
        mess.setContent(multipart);

        // Mengirim pesan menggunakan Transport
        Transport.send(mess);

        // Mengirim pesan menggunakan Transport
        Transport transport = session.getTransport("smtp");
        transport.connect("smtp.gmail.com", emailpengirim, sandiaplikasi);
        transport.sendMessage(mess, mess.getAllRecipients());
        transport.close();

        JOptionPane.showMessageDialog(this, "Notifikasi Email berhasil dikirim ke " + emailpenerima);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi Kesalahan dalam mengirim notifikasi email " + e.getMessage());
    }
    }//GEN-LAST:event_btnsendActionPerformed

    private void txtsubjekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubjekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubjekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(masuk_share.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(masuk_share.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(masuk_share.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(masuk_share.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new masuk_share().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Lnomor;
    private javax.swing.JButton btnsend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFormattedTextField txtdirektori;
    private javax.swing.JTextArea txtpesan;
    private javax.swing.JTextField txtsubjek;
    // End of variables declaration//GEN-END:variables
}
