/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adminkalender;

//import static com.sun.webkit.perf.WCFontPerfLogger.reset;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.conek;
import suratmasuk.masuk;


/**
 *
 * @author WIN 10
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
        datatable();
        reset();
    }
    public void reset(){
        txtnip.setText("");
        txtnama.setText("");
        txtjabatan.setText("");
        txtno.setText("");
        txtemail.setText("");
        Jlabel1.setText("");
    }
    public void datatable(){
        
        DefaultTableModel tbl=new DefaultTableModel();
       
        tbl.addColumn("nip");
        tbl.addColumn("nama");
        tbl.addColumn("jabatan");
        tbl.addColumn("no_tlp");
        tbl.addColumn("email");
        table.setModel(tbl);
        try{
            Statement statement=(Statement)conek.GetConnection().createStatement();
            ResultSet res=statement.executeQuery("SELECT * from admin ");
            while(res.next())
            {
                tbl.addRow(new Object[]{
                    
                    res.getString("nip"),
                    res.getString("nama"),
                    res.getString("jabatan"),
                    res.getString("no_tlp"),
                    res.getString("email")
            });
                table.setModel(tbl);
            }
        }catch (Exception e){
                JOptionPane.showMessageDialog(rootPane, "salah "+e);
        }      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bkalender = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        txtnip = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtjabatan = new javax.swing.JTextField();
        txtno = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        bsuratmasuk = new javax.swing.JLabel();
        bdelete = new javax.swing.JLabel();
        bedit = new javax.swing.JLabel();
        badd = new javax.swing.JLabel();
        bsuratkeluar = new javax.swing.JLabel();
        bcari = new javax.swing.JLabel();
        Jlabel1 = new javax.swing.JLabel();
        cover = new javax.swing.JLabel();
        bkegiatan = new javax.swing.JLabel();
        bprofil = new javax.swing.JLabel();

        bkalender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bkalender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bkalenderMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtsearch.setBackground(new java.awt.Color(217, 217, 217));
        txtsearch.setBorder(null);
        txtsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsearchMouseClicked(evt);
            }
        });
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsearchKeyTyped(evt);
            }
        });
        getContentPane().add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 170, 220, 20));
        getContentPane().add(txtnip, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 268, 170, -1));

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 170, -1));

        txtjabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjabatanActionPerformed(evt);
            }
        });
        getContentPane().add(txtjabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 170, -1));
        getContentPane().add(txtno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 170, -1));

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 170, -1));

        table.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIP", "NAMA", "JABATAN", "NO TELEPHON", "ALAMAT EMAIL"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 880, 440));

        bsuratmasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bsuratmasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsuratmasukMouseClicked(evt);
            }
        });
        getContentPane().add(bsuratmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 80, 30));

        bdelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bdelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bdeleteMouseClicked(evt);
            }
        });
        getContentPane().add(bdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 220, 30, 20));

        bedit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beditMouseClicked(evt);
            }
        });
        getContentPane().add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 260, 30, 30));

        badd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        badd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                baddMouseClicked(evt);
            }
        });
        getContentPane().add(badd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 606, 60, 20));

        bsuratkeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(bsuratkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 96, 80, 30));

        bcari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bcariMouseClicked(evt);
            }
        });
        getContentPane().add(bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 170, 50, 30));

        Jlabel1.setText("jLabel1");
        getContentPane().add(Jlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        cover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/admin.admin.png"))); // NOI18N
        cover.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        getContentPane().add(cover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1250, 710));

        bkegiatan.setText("jLabel1");
        bkegiatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bkegiatanMouseClicked(evt);
            }
        });
        getContentPane().add(bkegiatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 70, 30));

        bprofil.setText("jLabel1");
        getContentPane().add(bprofil, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 70, 190, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int baris = table.rowAtPoint(evt.getPoint());
        String nip = table.getValueAt(baris, 0).toString();
        txtnip.setText(nip);
        String nama = table.getValueAt(baris , 1).toString();
        txtnama.setText(nama);
        String jabatan = table.getValueAt(baris , 2).toString();
        txtjabatan.setText(jabatan);
        String no = table.getValueAt(baris , 3).toString();
        txtno.setText(no);
        String email= table.getValueAt(baris , 4).toString();
        txtemail.setText(email);
    }//GEN-LAST:event_tableMouseClicked

    private void bkalenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bkalenderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bkalenderMouseClicked

    private void bdeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bdeleteMouseClicked
        // TODO add your handling code here:
        String nip = txtnip.getText();
        String nama = txtnama.getText();
        String jabatan = txtjabatan.getText();
        String no = txtno.getText();
        String email = txtemail.getText();
        String pass = Jlabel1.getText();
        
        try{
            Statement statement = (Statement) conek.GetConnection().createStatement();
            statement.executeUpdate("DELETE from admin where nip =('" + nip +"');");
            JOptionPane.showMessageDialog(null, "data berhasil di HAPUS");
            txtnip.setText("");
            txtnama.setText("");
            txtjabatan.setText("");
            txtno.setText("");
            txtemail.setText("");
            Jlabel1.setText("");
            
            txtnip.requestFocus();  
        }catch (Exception t) {
            JOptionPane.showMessageDialog(null, "data gagal di HAPUS");
        }
        datatable();                              
    }//GEN-LAST:event_bdeleteMouseClicked

    private void beditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beditMouseClicked
        // TODO add your handling code here:
        
        String nip = txtnip.getText();
        String nama = txtnama.getText();
        String jabatan = txtjabatan.getText();
        String no = txtno.getText();
        String email= txtemail.getText();
        String password = Jlabel1.getText();
        
        try{
        Statement statement = (Statement) conek.GetConnection().createStatement();
            statement.executeUpdate("UPDATE admin SET nip='" + txtnip.getText() 
                    + "',nama='" + txtnama.getText() 
                    + "',jabatan='" + txtjabatan.getText() 
                    + "',no_tlp='" + txtno.getText() 
                    + "',email='" + txtemail.getText() 
                    + "',password='" + Jlabel1.getText() 
                    + "' where nip='"+ txtnip.getText() + "'");
            JOptionPane.showMessageDialog(this, "Berhasil di Edit");
        }catch (Exception t){
               
                }
        datatable();
    }//GEN-LAST:event_beditMouseClicked

    private void baddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baddMouseClicked
        // TODO add your handling code here:
         {                                        
      
        String nip = txtnip.getText();
        String nama = txtnama.getText();
        String jabatan = txtjabatan.getText();
        String no = txtno.getText();
        String email= txtemail.getText();
        String password= Jlabel1.getText();
        
          try{
              Statement statement = (Statement) conek.GetConnection().createStatement();
              statement.executeUpdate("insert into admin VALUES "
                      + "('" + nip + "','" + nama + "','" + jabatan + "','" + no +"','" + email + "','" + password+"')");
              datatable();
              reset();
          } catch (Exception e) {
              JOptionPane.showMessageDialog(null, e);
          }   
    }                              
    }//GEN-LAST:event_baddMouseClicked

    private void txtjabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjabatanActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void bsuratmasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsuratmasukMouseClicked
        // TODO add your handling code here:
        this.dispose();
                masuk a = new masuk();
                a.setVisible(true);
            
    }//GEN-LAST:event_bsuratmasukMouseClicked

    private void bcariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcariMouseClicked
        // TODO add your handling code here:
////////        try{
////////            Statement statement = (Statement) conek.GetConnection().createStatement();
////////            ResultSet res = statement.executeQuery("select * from admin where "
////////                    + "nama='" + txtsearch.getText() + "'");
////////            
////////            
////////            
////////            
////////            
////////            
////////            DefaultTableModel tbl = new DefaultTableModel();
////////           
////////            tbl.addColumn("nip");
////////            tbl.addColumn("nama");
////////            tbl.addColumn("jabatan");
////////            tbl.addColumn("no_tlp");
////////            tbl.addColumn("email");
////////             
////////            
////////            
////////            table.setModel(tbl);
////////            
////////            while (res.next()) {
////////                tbl.addRow(new Object[]{
////////                        
////////                        res.getString("nip"),
////////                        res.getString("nama"),
////////                        res.getString("jabatan"),
////////                        res.getString("no_tlp"),
////////                        res.getString("email"),
////////                       
////////                        
////////                });
////////                table.setModel(tbl);
////////            }
////////        }catch (Exception e) {
////////            JOptionPane.showMessageDialog(rootPane, "salah");
////////        }
    }//GEN-LAST:event_bcariMouseClicked

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtsearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyTyped
        // TODO add your handling code here:
        try{
            Statement statement = (Statement) conek.GetConnection().createStatement();
            ResultSet res = statement.executeQuery("select * from admin where nama like'%" + txtsearch.getText() +"%'");
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("NIP");
            tbl.addColumn("NAMA");
            tbl.addColumn("JABATAN");
            tbl.addColumn("NO TELEPHON");
            tbl.addColumn("ALAMAT EMAIL");
            
            
            table.setModel(tbl);
            
            while (res.next()) {
                tbl.addRow(new Object[]{
                        res.getString("nip"),
                        res.getString("nama"),
                        res.getString("jabatan"),
                        res.getString("no_tlp"),
                        res.getString("email")
                        
                });
                table.setModel(tbl);
            }
        }catch (SQLException e) {
            
        }
    }//GEN-LAST:event_txtsearchKeyTyped

    private void txtsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsearchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchMouseClicked

    private void bkegiatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bkegiatanMouseClicked
        // TODO add your handling code here:
        this.dispose();
                kegiatan a = new kegiatan();
                a.setVisible(true);
            
    }//GEN-LAST:event_bkegiatanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel1;
    private javax.swing.JLabel badd;
    private javax.swing.JLabel bcari;
    private javax.swing.JLabel bdelete;
    private javax.swing.JLabel bedit;
    private javax.swing.JLabel bkalender;
    private javax.swing.JLabel bkegiatan;
    private javax.swing.JLabel bprofil;
    private javax.swing.JLabel bsuratkeluar;
    private javax.swing.JLabel bsuratmasuk;
    private javax.swing.JLabel cover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtjabatan;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnip;
    private javax.swing.JTextField txtno;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
