/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adminkalender;

import adminkalender.edit;
import java.awt.Color;
import java.awt.Image;
import java.awt.Window;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import jdk.internal.org.jline.terminal.impl.jna.JnaSupportImpl;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import koneksi.conek;

/**
 *
 * @author USER
 */
public class profil extends javax.swing.JFrame {
    public PreparedStatement stat;
    public Connection connect;
    String filename,namafile,filefoto;

    /**pub
     * Creates new form profil
     */
    public profil() {
        initComponents();
        setdatauser();
        txtnip.setBackground(new Color(0,0,0,0));
        txtnip.setBorder(null);
        txtnama.setBackground(new Color(0,0,0,0));
        txtnama.setBorder(null);
        txtjabatan.setBackground(new Color(0,0,0,0));
        txtjabatan.setBorder(null);
        txtno.setBackground(new Color(0,0,0,0));
        txtno.setBorder(null);
        txtemail.setBackground(new Color(0,0,0,0));
        txtemail.setBorder(null);
    }
        public void setdatauser(){
        koneksi.Orang user = new koneksi.Orang();
        String nip = user.getUsername();
       try{
            Statement statement=(Statement)conek.GetConnection().createStatement();
            ResultSet res=statement.executeQuery("SELECT * from admin where nip = '"+ nip +"'");
            while(res.next())
            {
              txtnip.setText(res.getNString("nip"));
              txtnama.setText(res.getNString("nama"));
              txtjabatan.setText(res.getNString("jabatan"));
              txtno.setText(res.getNString("no_tlp"));
              txtemail.setText(res.getNString("email"));
              filefoto = res.getString("oplud");
            }
        }catch (SQLException e){
               
        }
       setFoto();
    }
        private void setFoto(){
            try {
    

    // Menggunakan getCanonicalPath() untuk mendapatkan path file yang valid
    

    // Membuat ImageIcon dari path file yang valid
    ImageIcon icon = new ImageIcon(filefoto);
    Image image = icon.getImage().getScaledInstance(profile.getWidth(), profile.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon ic = new ImageIcon(image);
    profile.setIcon(ic);
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Gagal menampilkan foto: " + e.getMessage());
}
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnip = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtjabatan = new javax.swing.JTextField();
        txtno = new javax.swing.JTextField();
        txtprof = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        bedit = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        bprofil = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cover = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnip.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtnip.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtnip.setEnabled(false);
        getContentPane().add(txtnip, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 510, 30));

        txtnama.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtnama.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtnama.setEnabled(false);
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 510, 30));

        txtjabatan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtjabatan.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtjabatan.setEnabled(false);
        getContentPane().add(txtjabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 510, 30));

        txtno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtno.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtno.setEnabled(false);
        getContentPane().add(txtno, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 510, 30));

        txtprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprofActionPerformed(evt);
            }
        });
        getContentPane().add(txtprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 210, 40));

        txtemail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtemail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtemail.setEnabled(false);
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 510, 30));

        bedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beditMouseClicked(evt);
            }
        });
        getContentPane().add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, 200, 20));

        profile.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 170, 160));

        bprofil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bprofilMouseClicked(evt);
            }
        });
        getContentPane().add(bprofil, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 190, 20));

        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, -1));

        cover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/PROFIL trbru.png"))); // NOI18N
        getContentPane().add(cover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void beditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beditMouseClicked
        // TODO add your handling code here:
        edit a = new edit(txtnama.getText(),txtnip.getText(),txtjabatan.getText(),txtno.getText(),txtemail.getText());
       
        
        a.setVisible(true);
        a.pack();
        a.setDefaultCloseOperation(edit.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_beditMouseClicked

    private void bprofilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bprofilMouseClicked
        // TODO add your handling code here:
       
    try {
    JFileChooser chooser = new JFileChooser();
    chooser.showOpenDialog(null);
    File f = chooser.getSelectedFile(); 

    // Menggunakan getCanonicalPath() untuk mendapatkan path file yang valid
    String filePath = f.getCanonicalPath();
    String filename;

    // Membuat ImageIcon dari path file yang valid
    ImageIcon icon = new ImageIcon(filePath);
    Image image = icon.getImage().getScaledInstance(profile.getWidth(), profile.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon ic = new ImageIcon(image);
    profile.setIcon(ic);

    profile.setIcon(ic);
    filename = f.getAbsolutePath();
    txtprof.setText(filename);

    String newpath = "src/profil/foto";
    File directory = new File(newpath);
    if (!directory.exists()) {
        directory.mkdirs();
    }

    // Mengambil ekstensi file
    String extension = filename.substring(filename.lastIndexOf('.') + 1);

    // Mendapatkan path tujuan yang valid
    File destinationFile = new File(newpath + "/" + f.getName());
    filename = String.valueOf(destinationFile);
    // Menyalin file dari sumber ke destinasi
    Files.copy(f.toPath(), destinationFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Gagal upload: " + e.getMessage());
}
    }//GEN-LAST:event_bprofilMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      String sql = "UPDATE admin set oplud = ? WHERE nip ='"+txtnip.getText()+"'";
try {
    connect = (Connection) conek.GetConnection(); // Mendapatkan koneksi
    PreparedStatement stat = connect.prepareStatement(sql); // Menggunakan PreparedStatement dari java.sql.Connection

    if (txtprof.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Anda belum memilih gambar");
    } else {
        stat.setString(1, txtprof.getText());
        stat.executeUpdate();
        JOptionPane.showMessageDialog(null, "Gambar berhasil disimpan");
    }
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    e.printStackTrace();
}
    
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprofActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bedit;
    private javax.swing.JLabel bprofil;
    private javax.swing.JLabel cover;
    private javax.swing.JButton jButton1;
    public javax.swing.JLabel profile;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtjabatan;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnip;
    private javax.swing.JTextField txtno;
    private javax.swing.JTextField txtprof;
    // End of variables declaration//GEN-END:variables
}
