/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adminkalender;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import koneksi.conek;

/**
 *
 * @author ASUS
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form signups
     */
    public register() {
        initComponents();
        txtnip.setBackground(new Color(0,0,0,0));
        txtnip.setBorder(null);
        txtnama.setBackground(new Color(0,0,0,0));
        txtnama.setBorder(null);
        txtjab.setBackground(new Color(0,0,0,0));
        txtjab.setBorder(null);
        txtnot.setBackground(new Color(0,0,0,0));
        txtnot.setBorder(null);
        txtmail.setBackground(new Color(0,0,0,0));
        txtmail.setBorder(null);
        txtpass.setBackground(new Color(0,0,0,0));
        txtpass.setBorder(null);
        btnregis.setBackground(new Color(0,0,0,0));
        btnregis.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnip = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtjab = new javax.swing.JTextField();
        txtnot = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        btnregis = new javax.swing.JButton();
        txtpass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnip.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtnip.setForeground(new java.awt.Color(0, 0, 102));
        txtnip.setBorder(null);
        getContentPane().add(txtnip, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 370, 20));

        txtnama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtnama.setForeground(new java.awt.Color(0, 0, 102));
        txtnama.setBorder(null);
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 380, 30));

        txtjab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtjab.setForeground(new java.awt.Color(0, 0, 102));
        txtjab.setBorder(null);
        getContentPane().add(txtjab, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 380, 30));

        txtnot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtnot.setForeground(new java.awt.Color(0, 0, 102));
        txtnot.setBorder(null);
        getContentPane().add(txtnot, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 380, 30));

        txtmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtmail.setForeground(new java.awt.Color(0, 0, 102));
        txtmail.setBorder(null);
        getContentPane().add(txtmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 380, 30));

        btnregis.setBorder(null);
        btnregis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisActionPerformed(evt);
            }
        });
        getContentPane().add(btnregis, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 140, 30));

        txtpass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpass.setForeground(new java.awt.Color(0, 0, 102));
        txtpass.setBorder(null);
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 380, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/signinss.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnregisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisActionPerformed
        // TODO add your handling code here:
        String nip = txtnip.getText().toString().trim();
        String nama = txtnama.getText().toString().trim();
        String jabatan = txtjab.getText().toString().trim();
        String nomor_telephone = txtnot.getText().toString().trim();
        String email = txtmail.getText().toString().trim();
        String password = txtpass.getText().toString().trim();
        
        if (password.isEmpty() || nip.isEmpty()) {
            JOptionPane.showMessageDialog(null, "NIP atau password tidak boleh kosong");
        }else{
            try{
                Connection c = conek.GetConnection();
                String sql = "INSERT INTO admin VALUES (?, ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, nip);
                p.setString(2, nama);
                p.setString(3, jabatan);
                p.setString(4, nomor_telephone);
                p.setString(5, email);
                p.setString(6, password);
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(null, "Akun berhasil dibuat");
            }catch(SQLException e){
                System.out.println("Error");
            }finally{
                this.dispose();
                login a = new login();
                a.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnregisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtjab;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnip;
    private javax.swing.JTextField txtnot;
    private javax.swing.JTextField txtpass;
    // End of variables declaration//GEN-END:variables
}
